name = "Dragon Pack"
author = "jcotton42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1a97a5f0485b3cc3d66af74436d91a59f86180fef29b624f8a3e7fbe9599a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
